import './globals.css'
import 'animate.css'
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from 'next'
import { ReduxProvider } from '@/redux/provider';
import { MAIN_FONT } from '@/styles/fonts';
import { ConfigProvider } from 'antd';
import { THEME } from '@/styles/theme';
import { ToastContainer } from 'react-toastify';
import SWRProvider from '@/components/provider/SWRProvider';

export const dynamic='force-static';
export const metadata: Metadata = {
  title: 'UETable',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${MAIN_FONT.className}`}>
      <body className='bg-underground'>
        <ReduxProvider>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: MAIN_FONT.style.fontFamily,
                // borderRadiusLG: 15
              },
              components: {
                Input: {
                  activeBg: THEME.SECONDARY_COLOR,
                  lineWidth: 2
                },
              }
            }}
          >
            <SWRProvider>
              {children}

              <ToastContainer
                position='bottom-right'
              />
            </SWRProvider>
          </ConfigProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}

