import './globals.css'
import type { Metadata } from 'next'
import { ReduxProvider } from '@/redux/provider';
import { MAIN_FONT } from '@/styles/fonts';
import { ConfigProvider } from 'antd';

export const metadata: Metadata = {
  title: 'UETable',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={MAIN_FONT.className}>
        <ReduxProvider>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: MAIN_FONT.style.fontFamily,
              },
            }}
          >
            {children}
          </ConfigProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
